/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TestReadingRouteImport } from './routes/test-reading'
import { Route as ZoneMapRouteImport } from './routes/zone-map'
import { Route as ZonePipelineIdRouteImport } from './routes/zone.$pipelineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TestReadingRoute = TestReadingRouteImport.update({
  id: '/test-reading',
  path: '/test-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneMapRoute = ZoneMapRouteImport.update({
  id: '/zone-map',
  path: '/zone-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonePipelineIdRoute = ZonePipelineIdRouteImport.update({
  id: '/zone/$pipelineId',
  path: '/zone/$pipelineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test-reading': typeof TestReadingRoute
  '/zone-map': typeof ZoneMapRoute
  '/zone/$pipelineId': typeof ZonePipelineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test-reading': typeof TestReadingRoute
  '/zone-map': typeof ZoneMapRoute
  '/zone/$pipelineId': typeof ZonePipelineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test-reading': typeof TestReadingRoute
  '/zone-map': typeof ZoneMapRoute
  '/zone/$pipelineId': typeof ZonePipelineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/test-reading' | '/zone-map' | '/zone/$pipelineId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/test-reading' | '/zone-map' | '/zone/$pipelineId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/test-reading'
    | '/zone-map'
    | '/zone/$pipelineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TestReadingRoute: typeof TestReadingRoute
  ZoneMapRoute: typeof ZoneMapRoute
  ZonePipelineIdRoute: typeof ZonePipelineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-reading': {
      id: '/test-reading'
      path: '/test-reading'
      fullPath: '/test-reading'
      preLoaderRoute: typeof TestReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone-map': {
      id: '/zone-map'
      path: '/zone-map'
      fullPath: '/zone-map'
      preLoaderRoute: typeof ZoneMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone/$pipelineId': {
      id: '/zone/$pipelineId'
      path: '/zone/$pipelineId'
      fullPath: '/zone/$pipelineId'
      preLoaderRoute: typeof ZonePipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TestReadingRoute: TestReadingRoute,
  ZoneMapRoute: ZoneMapRoute,
  ZonePipelineIdRoute: ZonePipelineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
